image: maven:3.5.0-jdk-8

before_script:
# install ssh-agent
- 'which ssh-agent || (apk add --update --no-cache openssh-client)'
# run ssh-agent
- 'eval $(ssh-agent -s)'
# add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
- echo "$SSH_PRIVATE_KEY" > /tmp/gitlab_ci_ssh
- chmod 600 /tmp/gitlab_ci_ssh
- ssh-add /tmp/gitlab_ci_ssh
# disable host key checking (NOTE: makes you susceptible to man-in-the-middle attacks)
# WARNING: use only in docker container, if you use it with shell you will overwrite your user's ssh config
- mkdir -p ~/.ssh
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - build
  - deploy

buildAndTest:
    stage: build
    script:
      - mvn verify
    artifacts:
      paths:
        - target/*.jar
      expire_in: 30min

deployStaging:
  stage: deploy
  only:
    - master
  script:
    - mvn package
    - mv target/*.jar card-service.jar
    - ssh root@206.189.119.154 'service card-service stop'
    - scp card-service.jar root@206.189.119.154:/opt/card-service/
    - ssh root@206.189.119.154 'service card-service start'
  artifacts:
    paths:
      - card-service.jar
    expire_in: 1d
  when: manual

deployProduction:
  stage: deploy
  only:
    - master
  script:
    - mvn package
    - mv target/*.jar card-service.jar
    - ssh root@167.99.248.168 'service card-service stop'
    - scp card-service.jar root@167.99.248.168:/opt/card-service/
    - ssh root@167.99.248.168 'service card-service start'
  artifacts:
    paths:
      - card-service.jar
    expire_in: 1d
  when: manual